### PR TITLE
Symlink set up to rocoto_view.py from EXPDIR

### PR DESCRIPTION
**Pull request by jkuang-exploro**

### CODE REVIEW

**Comment by flampouris** [comment]
@JianKuang-NOAA Please provide some context, what's this? How to use it? (Please update the README.md if necessary)

Is this PR connected with #63 ?

**Comment by flampouris** [comment]
This PR apparently does not break anything, but how can I use the tools?

**Comment by jkuang-exploro** [comment]
This PR has no direct modification of godas repository. However, it points to a new version of CROW. This will enable us to run rocoto_viewer.py under EXPDIR.

Normally after you submit your job, you do "rocotostat -w workflow.xml -d workflow.db"

Now you could do "./rocoto_viewer.py -w workflow.xml -d workflow.db"

This will give you better user experience than the standard "rocotostat". You could continue using that though.

**Comment by flampouris** [comment]
Nice, I am testing it.

**Review by guillaumevernieres — CHANGES_REQUESTED** [review]
@JianKuang-NOAA , could the rocoto_view.py be copied to a "bin" place, or to where the experiment is?
Nice interface, but we need an update to the high level README

**Comment by jkuang-exploro** [comment]
@guillaumevernieres Could you be more specific? You want a direct copy instead of symlink to the EXPDIR?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Could you be more specific? You want a direct copy instead of symlink to the EXPDIR?

link is fine, but I don't see it in the expdir.

**Comment by jkuang-exploro** [comment]
@guillaumevernieres  Couldn't you find "rocoto_viewer.py" within EXPDIR generated by CROW?

Here's the command of rocoto_viewer.py:

python rocoto_viewer.py -w workflow.xml -d workflow.db

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Couldn't you find "rocoto_viewer.py" within EXPDIR generated by CROW?
> 
> Here's the command of rocoto_viewer.py:
> 
> python rocoto_viewer.py -w workflow.xml -d workflow.db

Welcome back @JianKuang-NOAA !
Can you add the usage to the readme or wiki?
Planning to test this morning.

**Comment by jkuang-exploro** [comment]
@guillaumevernieres I've updated the readme.md

**Comment by guillaumevernieres** [comment]
@JianKuang-NOAA : You need to merge develop into your branch.

**Comment by jkuang-exploro** [comment]
@guillaumevernieres you are correct. I've just done it.

**Comment by guillaumevernieres** [comment]
@JianKuang-NOAA : I'm getting the following error,
workflow.db is not SQLite3 database file

Any special modules that we need to load?

**Comment by jkuang-exploro** [comment]
@guillaumevernieres Could you make sure workflow.db actually exist and non-empty? Does "rocotostat -w workflow.xml -d workflow.db" work?

**Comment by guillaumevernieres** [comment]
@JianKuang-NOAA : Ok, it works when I run rocoto once before. But you need to update the readme.

**Comment by jkuang-exploro** [comment]
@guillaumevernieres OK. Now fixed the readme again.

**Comment by guillaumevernieres** [comment]
@JianKuang-NOAA nice interface! Testing right now, all that is needed is an update to the readme.
step 1: rocotorun ...
step 2: rocoto_viewer.py ...

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres OK. Now fixed the readme again.

@JianKuang-NOAA forgot to commit? I don't see the changes.

**Comment by jkuang-exploro** [comment]
@guillaumevernieres could you see the changes?

**Comment by guillaumevernieres** [comment]
@JianKuang-NOAA nope, changes not pushed yet.

**Comment by jkuang-exploro** [comment]
@guillaumevernieres I've updated "Running the workflow" section and I could see it from my side.

"Or you could use "rocoto_viewer.py". Your terminal window needs to be wider than 125 chars
rocotorun -w workflow.xml -d workflow.db
python rocoto_viewer.py -w workflow.xml -d workflow.db"

**Comment by jkuang-exploro** [comment]
@guillaumevernieres could you please check again?

**Review by guillaumevernieres — APPROVED** [review]
:+1:

**Pull request merged**
