### PR TITLE
extend default time limit for some jobs.

### PR DESCRIPTION
**Pull request by jkuang-exploro**
resource tweak within EXPDIR enabled

## Description
extend default time limit for some jobs.
resource tweak within EXPDIR enabled

## Testing

./setup_case.sh -p HERA ../cases/3dvar.yaml test3dv
./make_rocoto_xml_for.sh /scratch1/NCEPDEV/global/Jian.Kuang/expdir/test3dvar

There will be a resource_sum.yaml in EXPDIR named test3dv. Changing resource allocation values (time, npe) there and redo CROW:

./setup_case.sh -p HERA -f ../cases/3dvar.yaml test3dv
./make_rocoto_xml_for.sh /scratch1/NCEPDEV/global/Jian.Kuang/expdir/test3dvar

You could see the resources being updated in workflow.xml as well as config files.

### CODE REVIEW

**Comment by flampouris** [comment]
@JianKuang-NOAA Why did we change `calc` to `icalc`?

**Comment by guillaumevernieres** [comment]
> @JianKuang-NOAA Why did we change `calc` to `icalc`?

Ha! Yes, I had the same question yesterday. Maybe that PR isn't so much about timing change but changing to icalc?

**Comment by jkuang-exploro** [comment]
icalc means "immediate value parsing". It would create "resource_sum.yaml" with the actual number of resource parameters (time, PEs). It's needed to enable resource tweak within EXPDIR.
@flampouris @guillaumevernieres

**Comment by flampouris** [comment]
Thanks @JianKuang-NOAA ! Please merge the develop into your branch without changing the clock times and I will review and merge it.

**Comment by guillaumevernieres** [comment]
> icalc means "immediate value parsing". It would create "resource_sum.yaml" with the actual number of resource parameters (time, PEs). It's needed to enable resource tweak within EXPDIR.
> @flampouris @guillaumevernieres

OK. Can you explain in more detail what "to enable resource tweak within EXPDIR" means?

**Comment by jkuang-exploro** [comment]
@guillaumevernieres There's some descriptions in the "Testing" section of the PR. 

Testing

./setup_case.sh -p HERA ../cases/3dvar.yaml test3dv
./make_rocoto_xml_for.sh /scratch1/NCEPDEV/global/Jian.Kuang/expdir/test3dvar

There will be a resource_sum.yaml in EXPDIR named test3dv. Changing resource allocation values (time, npe) there and redo CROW:

./setup_case.sh -p HERA -f ../cases/3dvar.yaml test3dv
./make_rocoto_xml_for.sh /scratch1/NCEPDEV/global/Jian.Kuang/expdir/test3dvar

You could see the resources being updated in workflow.xml as well as config files.

**Comment by jkuang-exploro** [comment]
@flampouris @guillaumevernieres Done merging of develop.

**Review by flampouris — CHANGES_REQUESTED** [review]
It doesn't seem that it works, see below.

[Stylianos.Flampouris@hfe03 CROW]$ ./setup_case.sh -p HERA ../cases/3dvar.yaml test_PR137
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/scratch2/NCEPDEV/marine/Stylianos.Flampouris/godas/workflow/CROW/utils/worktools.py", line 736, in setup_case
    skip_comrot,force_platform_rewrite)
  File "/scratch2/NCEPDEV/marine/Stylianos.Flampouris/godas/workflow/CROW/utils/worktools.py", line 253, in make_yaml_files_in_expdir
    config=crow.config.from_string(config_contents)
  File "/scratch2/NCEPDEV/marine/Stylianos.Flampouris/godas/workflow/CROW/crow/config/__init__.py", line 42, in from_string
    c=ConvertFromYAML(yaml.load(s, Loader=yaml.Loader),CONFIG_TOOLS,ENV)
  File "/apps/intel/intelpython3/lib/python3.6/site-packages/yaml/__init__.py", line 75, in load
    return loader.get_single_data()
  File "/apps/intel/intelpython3/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/apps/intel/intelpython3/lib/python3.6/site-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/apps/intel/intelpython3/lib/python3.6/site-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/apps/intel/intelpython3/lib/python3.6/site-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/apps/intel/intelpython3/lib/python3.6/site-packages/yaml/constructor.py", line 129, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/apps/intel/intelpython3/lib/python3.6/site-packages/yaml/constructor.py", line 86, in construct_object
    data = constructor(self, node)
  File "/apps/intel/intelpython3/lib/python3.6/site-packages/yaml/constructor.py", line 414, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!icalc'
  in "<unicode string>", line 485, column 21:
        - batch_memory: !icalc doc.godas_resource_table. ... 
                        ^

**Comment by jkuang-exploro** [comment]
@flampouris could you please checkout "develop" branch of CROW?

**Review by flampouris — CHANGES_REQUESTED** [review]
@JianKuang-NOAA With the updated CROW, it works. 

I will approve it, but first, for documentation reasons, please respond @guillaumevernieres question: 

> OK. Can you explain in more detail what "to enable resource tweak within EXPDIR" means?

**Comment by jkuang-exploro** [comment]
@flampouris @guillaumevernieres  It's a feature that enables users to change resource settings inside its EXPDIR. There will be a resource_sum.yaml in EXPDIR that serves as the central place to change resource settings (say, extend run time for job ticket). Changing it and rerun CROW with the -f option could change the resource setting for this experiment. 

How much "more details" are needed for this feature?

**Comment by flampouris** [comment]
@JianKuang-NOAA your initial explanation was sufficient for me, but you are adding some cool features, and I would like to be sure that all the 6 (+ the new) users of the system know that 1. this feature exists and 2. they have instructions how to use it. 

If it's documented somewhere at the CROW repo, just add a link, at the README.

**Comment by jkuang-exploro** [comment]
@flampouris @guillaumevernieres I've updated the README.md to include the instructions of resource updating inside EXPDIR. Please check and approve this PR if possible.

**Review by flampouris — APPROVED** [review]
:+1: 

Thank you for adding the option and provide the extra information.  

I approved it, but waiting for any extra input from anybody else. If there is nothing, I will merge it later tonight.

**Pull request merged**
