### PR TITLE
obscheck

### PR DESCRIPTION
**Pull request by mjhossen**
## Description
I have updated the godas-obssanitycheck.py that works for both daily or hourly/minutes data set. Please make your comments.

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
Your branch has conflicts with develop. 
Pull `develop` and `merge` it in your current branch then resolve the conflict.

**Review by guillaumevernieres — CHANGES_REQUESTED** [review]
See comment. Nees to be merged with `develop`

**Comment by mjhossen** [comment]
> 

I resolve the conflict

**Comment by guillaumevernieres** [comment]
> > 
> 
> I resolve the conflict

@mjhossen No, you did not. Look at the bottom of this page. It's written in large bold font ...

That's the workflow that you should be following:
```console
git checkout develop
git pull
git checkout feature/obssanitycheck
git merge develop
```
It will tell you what files are in conflict, fix these files, commit and push to github.

**Comment by guillaumevernieres** [comment]
@mjhossen , thanks for submitting your work, but I'm going to close this pr for 2 reasons:
- Your merging didn't work, I suggest you start off develop, create a new branch and add your new features in the new branch. There are other ways, but considering you are only modifying 1 file, that's the simpler way to fix this.  
- This hasn't been unforced yet, but a pull request should close an issue. I know I have not followed that rule, so shame on me. Before you start coding next week, create an issue in github explaining what feature you will be adding. Once you are confident your code addresses the issue and is as clean as you can make it, then submit a PR.

**Pull request closed without merging**
