### PR TITLE
switch to zstar + bugfixes ...

### LINKED ISSUE #187: Missing link to module files on Orion
ufs/INSTALL/orion.intel.fcst should point to orion.fcst

### LINKED ISSUE #188: Update mom's config to be the same as SPEAR, switch from ALE to Z*

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Description
The current setup for the vertical convolution only works well for z*. This can be revisited in the future, but in the meantime we are copy/pasting the SPEAR MOM_input and keeping the vertical convolution setup the same between `mom6-sis2`, `UFS` and `GEOS`. The main purpose of this PR is to switch from ALE to Z* (in MOM_override) and update of MOM_input to be the same as the one used in SPEAR. 

### Issue(s) addressed
- closes #188 
- closes #187 

## Testing
Showing global MAE for ssh. 
green: This PR's config
black: what's in `develop`
red: `mom6-sis2` configured like `SPEAR`
 
obs_absolute_dynamic_topography

### CODE REVIEW

**Comment by clouden90** [comment]
@guillaumevernieres : Thx for the updating! Will test these setups using the latest DATM-MOM6-CICE6 too. Quick question: do you use these new setups for the fcst step too (not only da step), right?

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres : Thx for the updating! Will test these setups using the latest DATM-MOM6-CICE6 too. Quick question: do you use these new setups for the fcst step too (not only da step), right?

yes, used for both, DA and fcst. But, you could do an ale forecast from the same restarts.

**Comment by clouden90** [comment]
> > @guillaumevernieres : Thx for the updating! Will test these setups using the latest DATM-MOM6-CICE6 too. Quick question: do you use these new setups for the fcst step too (not only da step), right?
> 
> yes, used for both, DA and fcst. But, you could do an ale forecast from the same restarts.

Thx. Same as I thought. Will pass this PR once I test with DATM-MOM6-CICE6.

**Review by clouden90 — APPROVED** [review]
Tested with DATM-MOM6-CICE6. Ok for now.

**Comment by guillaumevernieres** [comment]
@clouden90 , @jkbk2004 : why was this pr closed?

**Comment by clouden90** [comment]
> @clouden90 , @jkbk2004 : why was this pr closed?

Oops I am not sure why.  I just did history clean this afternoon, not sure if this is related to my history clean activity. Can you reopen this PR?

**Comment by jkbk2004** [comment]
@guillaumevernieres I am not able to activate re-open button at bottom. I am not sure leaving comment may reactivate reopen button.

**Comment by jkbk2004** [comment]
@clouden90 @guillaumevernieres maybe we need to revert the merge and reissue the PR?

**Comment by guillaumevernieres** [comment]
> @clouden90 @guillaumevernieres maybe we need to revert the merge and reissue the PR?

@jkbk2004 , don't it's a simple manual merge.I'll deal with it after a pile of other thing ...

**Pull request closed without merging**
