### PR TITLE
Feature/model updates

### LINKED ISSUE #170: Update the prep scripts and templates to conform the updated DATM-MOM6-CICE5

### PR DESCRIPTION
**Pull request by flampouris**
## Description
The scripts to setup and run the DATM-MOM6-CICE5 at develop branch, have been updated. 

### Issue(s) addressed

- fixes #170 

## Testing
Run fcst_only and 3dvar_only with the DATM-MOM6-CICE5

### CODE REVIEW

**Review by JessicaMeixner-NOAA — APPROVED** [review]
All these changes look okay to me.  @jkbk2004 might want to double check the diag_table because I think he added some of those for the python output scripts he was using.

**Comment by jkbk2004** [comment]
@flampouris @JessicaMeixner-NOAA that's right. it will be good to keep area_t vmo umo e hfds PRCmE in diag table. mom6-tools applications require these variables in mom6 verification plots.

**Comment by flampouris** [comment]
> @flampouris @JessicaMeixner-NOAA that's right. it will be good to keep area_t vmo umo e hfds PRCmE in diag table. mom6-tools applications require these variables in mom6 verification plots.

@jkbk2004 Could you add them, please?

**Review by jkbk2004 — APPROVED** [review]

**Comment by flampouris** [comment]
Thank you for the review, y'all!!!

**Pull request merged**
