### PR TITLE
Modified icec_prep_obs.sh

### PR DESCRIPTION
**Pull request by YanHao-NOAA**
**Description**

**Issue(s) addressed**

**Testing**

Old feature has problems for merging, so created this new feature

### CODE REVIEW

**Review by jkbk2004 — APPROVED** [review]

**Review by flampouris — CHANGES_REQUESTED** [review]
1. The JJOB_OBS_PREP has to be modified. 

Replace the module in the file with the following: 

`module use -a /scratch2/NCEPDEV/marine/Todd.Spindler/save/modulefiles`
  
`module load anaconda/1.0.0`

2. At the soca-bundle at line 54, the CMakeLists.txt has to point to develop branch.
`ecbuild_bundle( PROJECT ioda-converters GIT "https://github.com/JCSDA/ioda-converters.git" UPDATE BRANCH develop )`

@guillaumevernieres is it possible that we point to the develop for the ioda-converters?

**Comment by flampouris** [comment]
@YanHao-NOAA Please merge develop branch into yours and test the code, when it's done, let us know to review the code and finish this PR.

**Comment by YanHao-NOAA** [comment]
Merged develop to feature/process_ice, please review, thanks

**Comment by flampouris** [comment]
The PR is pointing to the wrong branch, closing it now. A new PR has to be open.

**Comment by jkbk2004** [comment]
@flampouris @YanHao-NOAA maybe I can test python-workflow script to see how feature/process_ice branch goes and validate the python-workflow script.

**Comment by YanHao-NOAA** [comment]
Jong, Yes, Please go ahead and test this.

Thanks
Yan

**Comment by flampouris** [comment]
This specific PR has been canceled because it was pointed to the wrong feature branch.

 Check the #115

**Pull request closed without merging**
