### PR TITLE
Feature/update conda

### PR DESCRIPTION
**Pull request by jkbk2004**
## Description
anaconda3 update to allow flexible addition of python packages in the project

Provide a detailed description of what this PR does.  
1. installed anaconda3 with mom6-tools and xskillscore: :/scratch2/NCEPDEV/marineda/Jong.Kim/anaconda3
2. mom6-tools and xskillscore scripts are allowed with new anaconda3
3. moved modulefiles location to marineda: /scratch2/NCEPDEV/marineda/Jong.Kim/save/modulefiles
4. updated hera.anaconda and godas.python in modulefiles directory

## Testing
tested with 3dvar case and post processing. But please confirm to see any issue to run the system on hera!

### CODE REVIEW

**Comment by ShastriPaturi** [comment]
@jkbk2004 is the PR now ready to be tested again?

**Comment by jkbk2004** [comment]
@ShastriPaturi Yep, anaconda3/mom6-tools/xskillscore side works ok. So, try to run and you can add xskillscore scripts as well.

**Review by ShastriPaturi — APPROVED** [review]
The PR does what it promises

**Review by flampouris — APPROVED** [review]
:+1:

**Pull request merged**
