### PR TITLE
Add DistancefromCoast filter to icec_ssmis yamls

### LINKED ISSUE #361: Add DistancefromCoast filter to icec_ssmis*yaml
distancefromCoast filter is missing from icec_ssmis_f<17,18>_<north,south>.yaml

### PR DESCRIPTION
**Pull request by ShastriPaturi**
## Description
This PR add the the Distance fromCoast filters to icec_ssmis_<f17,18>_<north,south>.yaml

### Issue(s) addressed
Closes #361

### CODE REVIEW

**Review by liuxiao37k — COMMENTED** [review]
I see @mjhossen 's comment on adding this filter to solve the icepack issues: https://github.com/NOAA-EMC/godas/issues/298#issuecomment-1194599645

My question is: is this filter essentially to remove a large amount (probably a majority?) of ice obs considering 100 km from each side of the costs could span dozens of grid cells in the polar regions? I recall that disabling ice DA also helps get around the icepack issue. I wonder if this is essentially the same machanism. @mjhossen Did you get a chance to see how many more obs were rejected by adding this filter?

**Comment by ShastriPaturi** [comment]
> I see @mjhossen 's comment on adding this filter to solve the icepack issues: [#298 (comment)](https://github.com/NOAA-EMC/godas/issues/298#issuecomment-1194599645)
> 
> My question is: is this filter essentially to remove a large amount (probably a majority?) of ice obs considering 100 km from each side of the costs could span dozens of grid cells in the polar regions? I recall that disabling ice DA also helps get around the icepack issue. I wonder if this is essentially the same machanism. @mjhossen Did you get a chance to see how many more obs were rejected by adding this filter?

@liuxiao37k this is one the the solutions. I agree that 100km is debatable. Disabling iceDA, restoring the ice thickness to GIOMAS ice thickness data and removing sst obs from polar regions or removing sst obs completely for 5 ish days prior to problem day and 2-3 days after after have worked. The last method was infact applied during the 40 year reanalysis and also for the CPC transition.

**Comment by liuxiao37k** [comment]
> @liuxiao37k this is one the the solutions. I agree that 100km is debatable. Disabling iceDA, restoring the ice thickness to GIOMAS ice thickness data and removing sst obs from polar regions or removing sst obs completely for 5 ish days prior to problem day and 2-3 days after after have worked. The last method was infact applied during the 40 year reanalysis and also for the CPC transition.

@ShastriPaturi I see. thanks for the info!

**Comment by mjhossen** [comment]
@liuxiao37k Here is the output before and after implementing **distance_from_coast** filter on icec_ssmis observations.
**Without filter**:
```
QC icec_ssmis_f17_north sea_ice_area_fraction: 146567 passed out of 429612 observations.
```
**With filter** (less observation passed out):
```
QC icec_ssmis_f17_north sea_ice_area_fraction: 112662 passed out of 429612 observations.
```

**Comment by liuxiao37k** [comment]
> @liuxiao37k Here is the output before and after implementing **distance_from_coast** filter on icec_ssmis observations. **Without filter**:
> 
> ```
> QC icec_ssmis_f17_north sea_ice_area_fraction: 146567 passed out of 429612 observations.
> ```
> 
> **With filter** (less observation passed out):
> 
> ```
> QC icec_ssmis_f17_north sea_ice_area_fraction: 112662 passed out of 429612 observations.
> ```

Thank you @mjhossen. Good to know!

**Review by guillaumevernieres — APPROVED** [review]

**Comment by guillaumevernieres** [comment]
@liuxiao37k and @mjhossen , are you OK with these changes?

**Comment by liuxiao37k** [comment]
> @liuxiao37k and @mjhossen , are you OK with these changes?

The icepack issues have been bothering me too. I'd be willing to do anything to stop those errors! So I am OK!

**Comment by mjhossen** [comment]
> @liuxiao37k and @mjhossen , are you OK with these changes?

Yes, the filter helps to resolve icepack problem occurred in my current experiments.

**Pull request merged**
