### PR TITLE
convert RTOFS obs binary to IODA v2

### LINKED ISSUE #371: convert RTOFS obs binary to IODA v2
This issue is linked to [PR #370 ](https://github.com/NOAA-EMC/godas/pull/370)

### PR DESCRIPTION
**Pull request by YongzuoLi-NOAA**
## Description
This PR will convert RTOFS operational observation binary data into IODA v2. The shell script, Fortran, and python codes are used.
This PR is linked to [issues #371](https://github.com/NOAA-EMC/godas/issues/371)

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- closes #371

## Dependencies
IODA V2 library

### CODE REVIEW

**Review by guillaumevernieres — CHANGES_REQUESTED** [review]
We're probably not going to test your code @YongzuoLi , but could you: 
- add the Fortran code that does the bin to ascii conversion ?
- rename `readme` to `README.md` and add a bit of documentation (build instruction, example usage, ...)

**Review by ShastriPaturi — CHANGES_REQUESTED** [review]
@YongzuoLi, can you please create an issue and link to it in the description?

**Comment by YongzuoLi-NOAA** [comment]
@ShastriPaturi [issue #371](https://github.com/NOAA-EMC/godas/issues/371)

**Comment by YongzuoLi-NOAA** [comment]
> We're probably not going to test your code @YongzuoLi , but could you:
> 
> * add the Fortran code that does the bin to ascii conversion ?
> * rename `readme` to `README.md` and add a bit of documentation (build instruction, example usage, ...)

done

**Review by guillaumevernieres — APPROVED** [review]

**Pull request merged**
