### PR TITLE
Remove large files

### PR DESCRIPTION
**Pull request by clouden90**
## Description

Remove UFS input files. INPUT files can be found locally on Hera/Orion.

### CODE REVIEW

**Comment by ShastriPaturi** [comment]
What is the location of the INPUT files locally on orion/hera?

**Comment by jkbk2004** [comment]
@clouden90 can you make sure all the files are current at /work/noaa/marine/marineda/ufs?

**Comment by guillaumevernieres** [comment]
Not that simple @clouden90 , the history needs to be cleaned as well ...

**Comment by clouden90** [comment]
> Not that simple @clouden90 , the history needs to be cleaned as well ...



> Not that simple @clouden90 , the history needs to be cleaned as well ...

@guillaumevernieres : I tried to follow with [this](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/removing-sensitive-data-from-a-repository). I can remove it from history, but it did not allow me to push back to develop. Do you have any tips?

**Comment by clouden90** [comment]
> @clouden90 can you make sure all the files are current at /work/noaa/marine/marineda/ufs?

@jkbk2004 @ShastriPaturi , On Orion: /work/noaa/marine/marineda/ufs
                                             On Hera: /scratch2/NCEPDEV/marine/marineda/ufs

**Review by jkbk2004 — APPROVED** [review]
No problem to approve the PR.

**Comment by guillaumevernieres** [comment]
@jkbk2004 : The issue was only partially addressed, why was that branch merged? Your binary files are still in the history ...

**Pull request merged**
