### PR TITLE
Feature/update setup

### PR DESCRIPTION
**Pull request by flampouris**
## Description
Updates for the setup_godas.py:

1. CLONE_DIR is set as a system variable internally to the py script
2. the user_id was eliminated
3. The run directory (SCRUB) could be defined at the test.setup_godas.yaml
4. mom6tools are copied to the bin dir
5. Readme is updated

## Testing
Use the setup_godas.py according to the instructions to the README, the installed system should go through the test and the driving python scripts for the mom6 plots should be copied to the build/bin directory.

### CODE REVIEW

**Review by jkbk2004 — APPROVED** [review]
I will sync the setup script in common directory for the mom6-tools. will update mom6-tools readme in next pr to point path to build/bin/ as well.

**Comment by flampouris** [comment]
Jong, this PR is for:

1. Syncing common with the github repository
2. And copies your "mains" for mom6tools to the build/bin

As soon, we have this in, I will have the PR for the JJOB_POST, it's
readish.

**Comment by jkbk2004** [comment]
@flampouris There is a chance people might get confused. When they get into test directory, they already cloned godas and got CLONE_DIR in their setenv. So, following changes in this branch may make sense to them. I think we can use the script in this branch to update one in common directory.

test.setup_godas.py
 if __name__ == '__main__':
     #1. Read directory paths, build/ctest option, and workflow name ------------
+    try:  
+        CLONE_DIR=os.environ.get('CLONE_DIR')
+    except KeyError:
+        print ("Please set the environment variable CLONE_DIR")
+        sys.exit(1)
+
     with open('test.setup_godas.yaml') as input_file:
          input = yaml.load(input_file)
-    CLONE_DIR = input.get('CLONE_DIR')
     PROJECT_DIR = input.get('PROJECT_DIR')
     WORKFLOW_NAME = input.get('WORKFLOW_NAME')
     SKIP_BUILD= input.get('SKIP_BUILD')
     FIX_SCRUB= input.get('FIX_SCRUB')
     SCRUB= input.get('SCRUB')
     USER = os.getenv('USER')
-    os.environ["CLONE_DIR"] = CLONE_DIR
     path = os.getcwd()
     
     print ("----- Current work directory is %s" % path)
 
-    if not SKIP_BUILD :
-        if os.path.isdir(CLONE_DIR): delete_dir(CLONE_DIR)
-    
+    if not SKIP_BUILD :    
         #1. Setup GODAS system at CLONE_DIR ------------------------------------
         print ('-----------Setup GODAS system at:',CLONE_DIR)
-        os.system("git clone https://github.com/NOAA-EMC/godas.git "+CLONE_DIR)
         os.chdir(CLONE_DIR)
         os.system("git submodule update --init --recursive")

test.setup_godas.yaml
-CLONE_DIR: #set the clone directory

**Comment by jkbk2004** [comment]
@flampouris my previous comment is a little mess in git edit. I mean the lines to CLONE_DIR ... and we can simply drop CLONE_DIR line in yaml file.

    #1. Read directory paths, build/ctest option, and workflow name ------------                                        
    try:
        CLONE_DIR=os.environ.get('CLONE_DIR')
    except KeyError:
        print ("Please set the environment variable CLONE_DIR")
	sys.exit(1)

    with open('test.setup_godas.yaml') as input_file:
         input = yaml.load(input_file)
    PROJECT_DIR = input.get('PROJECT_DIR')
    WORKFLOW_NAME = input.get('WORKFLOW_NAME')
    SKIP_BUILD= input.get('SKIP_BUILD')
    FIX_SCRUB= input.get('FIX_SCRUB')
    SCRUB= input.get('SCRUB')
    USER = os.getenv('USER')
    path = os.getcwd()
    print ("----- Current work directory is %s" % path)

    if not SKIP_BUILD :
        #1. Setup GODAS system at CLONE_DIR ------------------------------------                                        
        print ('-----------Setup GODAS system at:',CLONE_DIR)
        os.chdir(CLONE_DIR)

**Comment by jkbk2004** [comment]
@flampouris I updated the script in common with ones in this branch. You may check max_runs   = 16*2 to set as you want to use for your daily setup/test runs.

**Comment by flampouris** [comment]
@jkbk2004 I just went through your comment, I added the conditional statement if the CLONE_DIR is defined on as system variable to be used otherwise to the use the one from the yaml file. 

Let me know what you think with this approach.

**Review by jkbk2004 — APPROVED** [review]
This is nice option!

**Pull request merged**
