### PR TITLE
Feature/fcst ens

### PR DESCRIPTION
**Pull request by flampouris**
## Description

With this PR, the forecast case and all the cases using the forecast are able to run an ensemble by modifying the cases/*.yaml, by adding the NO_ENS_MBR and GROUPS, see the workflow/cases/fcst_only.yaml for an example.

This update is focused on DATM-MOM6-CICE5 model.

By adding ensemble model run capability we are able to run an ensemble forecast or/and DA through the workflow.

### Issue(s) addressed
Ensemble forecast is now supported

## Testing
To test, the reviewers should run  for the  DATM-MOM6-CICE5 model, the following cases: 

1. The forecast case with one member and get identical results with the develop forecast case.
2. The forecast case with multiple members and get identical results among the members and the develop forecast case.
3. The 3dvar and get identical results with the develop 3dvar case.

Known Issues:
Select NO_ENS_MBR, GROUPS in such a way mod(NO_ENS_MBR, GROUPS)=0

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
@flampouris  

So I ran tests last night, but something didn't go right.  I haven't had enough time to figure out what went wrong (if it was user error or what).  

My run directories are in: 
/scratch1/NCEPDEV/stmp2/Jessica.Meixner/Jessica.Meixner/rundir

Testing new code: 
wkflwtestens001    -- fcst 2 members 
 wkflwtestens002  --fcst 1 member 
wkflwtestens3dVar    --- 3D var 
(exe is in /scratch2/NCEPDEV/stmp3/Jessica.Meixner/testgodasens01) 


Dev branch for comparison: 
workflowtest001  -- fcst only 
 workflowtest3dVar --- 3Dvar 
(exe dirs are in /scratch2/NCEPDEV/stmp3/Jessica.Meixner/testgodasdev) 

The 3D var comparisons said these files are different: 
rundir]$ diff -r -q wkflwtestens3dVar workflowtest3dVar
Files wkflwtestens3dVar/2011100112/Data/2011100112/ioda.sst.avhrr19_l3u.nesdis.24h.nc and workflowtest3dVar/2011100112/Data/2011100112/ioda.sst.avhrr19_l3u.nesdis.24h.nc differ
Files wkflwtestens3dVar/2011100112/Data/2011100112/ioda.sst.avhrrmta_l3u.nesdis.24h.nc and workflowtest3dVar/2011100112/Data/2011100112/ioda.sst.avhrrmta_l3u.nesdis.24h.nc differ
Files wkflwtestens3dVar/2011100112/Data/2011100112/ioda.sst.windsat_l3u.ghrsst.24h.nc and workflowtest3dVar/2011100112/Data/2011100112/ioda.sst.windsat_l3u.ghrsst.24h.nc differ
Only in wkflwtestens3dVar: 2011100112_IC

The new code with 2 members the forecast jobs do not appear to have run.  I completely forgot to look earlier so maybe it literally was just a matter of the jobs not going through, but my crontab still had all the different ones this morning.  

The code itself looks fine to me so I see no issues except for that you wanted the 3 tests to be run and work and right now I don't see that they do.

**Comment by flampouris** [comment]
Thank you @JessicaMeixner-NOAA I will check the ensemble run and see what's on. The 3dvar has to do with some preprocessing, I think that's fine.

:beach_umbrella:

**Comment by flampouris** [comment]
Can somebody else run the fcst case and let me know if it went through?

./setup_case.sh -p HERA ../cases/fcst_only.yaml test_ens_fcst_PR

Jessica's test seems it never went over the fcst_prep, and I want to be sure that the issue is not the setup of the "case".

**Comment by jkbk2004** [comment]
@flampouris I will try to make a test run.

**Review by jkbk2004 — APPROVED** [review]
fcst_prep.pgrp* and fcst_run.pgrp* ran thru ok!

**Comment by flampouris** [comment]
Thank y'all for the review.

**Pull request merged**
