### PR TITLE
Update obs yamls

### LINKED ISSUE #383: Update obs yaml
# Description
This PR https://github.com/JCSDA-internal/ioda/pull/776 was merged and will break our systems.

# Todo
Update the `obs yaml` files here:
- https://github.com/NOAA-EMC/godas/tree/develop/soca/obs
- https://github.com/NOAA-EMC/GDASApp/tree/develop/parm/soca/obs/config 

# Tools
About the script to convert the old obs yamls:
https://github.com/JCSDA-internal/ioda/issues/713#issuecomment-1242568026

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Description

Update obs `yamls` to follow new convention from [ioda PR 776](https://github.com/JCSDA-internal/ioda/pull/776).

### Issue(s) addressed
- fixes #383 

## Testing

**NOT TESTED**

### CODE REVIEW

**Comment by mjhossen** [comment]
what is H5file? Does it mean file format is hdf5?

**Comment by mjhossen** [comment]
Obs yamls are working smoothly in the new test.

**Comment by mjhossen** [comment]
Test is failed with the new obs yaml files. It seems
$(experiment_dir)/current_cycle/$(experiment).sss_smap_jpl.window_begin.nc4 is wrong.
The old : $(experiment_dir)/{{current_cycle}}/sss_smap_jpl.{{window_begin}}.nc4 could be right.

**Comment by guillaumevernieres** [comment]
> what is H5file? Does it mean file format is hdf5?

yes

**Comment by guillaumevernieres** [comment]
> Test is failed with the new obs yaml files. It seems (experimentdir)/currentcycle/(experiment).sss_smap_jpl.window_begin.nc4 is wrong. The old : $(experiment_dir)/{{current_cycle}}/sss_smap_jpl.{{window_begin}}.nc4 could be right.

Do what I say, not what I do ... Or something. `No need to test your PR before submitting them` said absolutely no one :)
I'll actually look at what I did @mjhossen , thanks for checking.

**Comment by guillaumevernieres** [comment]
Sorry about that @mjhossen , could you pull and try again? I added back the `{{}}` brackets around `current_cycle` and `window_begin`.

**Review by liuxiao37k — APPROVED** [review]
love "added {{}} and added more {{}}" :)

**Review by ShastriPaturi — APPROVED** [review]
Tested 1 cycle.
Thanks @mjhossen for the fix.

**Comment by mjhossen** [comment]
I build the develop branch and run a test with a cycle. Run the model without problem.

**Review by mjhossen — APPROVED** [review]

**Pull request merged**
