### PR TITLE
set xscale

### LINKED ISSUE #377: EVA: add an x log scale option
# Description
1 - fork `eva`
2 - work on adding an option for the type of x scale to be used in the figure
3 - submit PR into the develop branch of the original eva repository

### PR DESCRIPTION
**Pull request by mjhossen**
## Description
This PR is for modifying EVA with a function (set_xscale) to set x log scale. The function allows us to plot figures on log scale in x as well. 

### Issue(s) addressed
- fixes #377

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
@mjhossen I think this should probably be done in a fork of https://github.com/danholdaway/eva/ and a PR issued to there (may need to ask me/Dan to issue the PR for you once the branch is in your fork)

**Comment by guillaumevernieres** [comment]
Could you please read the issue @mjhossen ...

**Comment by mjhossen** [comment]
Ok, I will do it in the fork of Dan.

**Comment by mjhossen** [comment]
> @mjhossen I think this should probably be done in a fork of https://github.com/danholdaway/eva/ and a PR issued to there (may need to ask me/Dan to issue the PR for you once the branch is in your fork)

I create a pull request (https://github.com/danholdaway/eva/pull/46) in the fork of Dan.

I am not allowed to add a reviewer in the PR.

**Pull request closed without merging**
