### PR TITLE
feature/gfs2datm

### PR DESCRIPTION
**Pull request by hyunchul386**
## Description

Adding a DATM flux forcing conversion package

### Issue(s) addressed

adding a code and script for conversion from GFSv2 fluxes to DATM format of GFS_DATM

## Testing
This code and scripts have been test at Nigara and Hera

### CODE REVIEW

**Review by guillaumevernieres — APPROVED** [review]
Thanks @hyunchul386

**Review by guillaumevernieres — CHANGES_REQUESTED** [review]
... oops .. reverting

**Review by guillaumevernieres — COMMENTED** [review]
It looks like they are empty, but lets not add binary files to the repo. Remove these grib2 files:
DATM_FORCING/GFS/Reanal/*.grib2

and anyother binary files, in case I missed more.

**Comment by hyunchul386** [comment]
The directory of /Reanal was deleted, which included binary files

**Review by guillaumevernieres — COMMENTED** [review]
an other one here: DATM_FORCING/GFS/conv_gfs2datm_long_beta4

**Comment by hyunchul386** [comment]
Got it and now the executable file was removed.

**Review by guillaumevernieres — APPROVED** [review]
:+1:

**Pull request merged**
