### PR TITLE
Orion porting

### PR DESCRIPTION
**Pull request by jkuang-exploro**
## Description
This PR addresses the Orion adaptation issue. Please test run on both Orion and Hera.

Orion nck utility remains problematic. Need to address it later.

### CODE REVIEW

**Comment by jkbk2004** [comment]
@JianKuang-NOAA you have to include me for review. hera.anaconda is included in load_godas_modules.sh. That causes some trouble on hera:  Lmod has detected the following error: Cannot load module "intelpython/3.6.8" because these module(s) are loaded: anaconda. hera.anaconda is needed only in a few script like JJOB_OBS_PREP and JJOB_POST. In develop branch, it comes with godas.python. It should be good to separate hera.anaconda out from load_godas_modules.sh and put it into another shell script and call it from JJOB_OBS_PREP and JJOB_POST.

**Comment by jkbk2004** [comment]
@JianKuang-NOAA actually, it is going thru if I load  hera.anaconda as last one in load_godas_modules.sh. Let me test more.

**Review by jkbk2004 — APPROVED** [review]
I approve this PR. Tested ok on Hera!

**Comment by flampouris** [comment]
+1

>

**Pull request merged**
