### PR TITLE
Feature/letkf merge

### PR DESCRIPTION
**Pull request by jkbk2004**
## Description
This is based on PR#152 to allow ensemble of perturbed ICs and LETKF

## Testing
- This feature branch needs to be tested with feature/letkf_merge branch of soca-config. After merge of this PR, the soca-config feature branch can be merged to develop branch as well.
- Two workflow/cases are needed to be tested for this PR: ic_ens.yaml  letkf_only_exp.yaml

How were these changes tested?
- Since this PR involves multiple workflow cases. test.multi_cases.py can be utilized available in test directory.
- Example test.multi_cases.yaml can be found at /scratch2/NCEPDEV/marineda/Jong.Kim/test.* on hera.
- 3dvar, fcst_only, hofx3d cases were also tested. For robust confirmation, these cases can be added for test.
- On hera, rocoto often conflicts with job scheduler during tests: rocotocomplete and rocotorewind commands help to handle the rocoto issues.

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names for the automated TravisCI tests to pass

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on JCSDA/soca-bundle/pull/<pr_number>
- waiting on JCSDA/oops/pull/<pr_number>

### CODE REVIEW

**Comment by flampouris** [comment]
😄

**Review by clouden90 — APPROVED** [review]
LETKF workflow test passed on Hera with 10 and 40 ensemble members. The LETKF workflow also works on Orion with some manual modification. I can approve this PR for now (mainly for the workflow part) but there are a few concerns/thoughts about the LETKF and would require further works to investigate:

1.	The vertical coordinate in each ensemble runs is different (vertical grid thickness is varying in different runs), and currently wrong vertical coordinate was used in letkf.yaml (line28: vert1d: {file: Vertical_coordinate.nc, variable: Layer}, this is just a reference and can not reflect real vertical coordinate in mom6 output). This needs to be solved. Perhaps use fixed z* coordinate mom6 output (defined in diag_table) might be a quick way.

2.	Related to (1), currently the results from LETKF look wired to me (checked ocn.ana.*.nc and ocn.bkg.*.nc) and I suspect it is due to the problem I mentioned in (1). We should take deep look into it later. 

3.	More works are needed to make the workflow works on both Hera and Orion. Currently the workflow works fine on Hera but not Orion. I can hot-wire the job script now to make it work on Orion but eventually we should have a workflow works for both Hera/Orion.

**Comment by flampouris** [comment]
@clouden90 's comment 1: Use the recenter app of SOCA. In the feature/letkf branch there is a ready example for preparing it. 

🏖️ 😄 ⛱️ 🍹

**Comment by guillaumevernieres** [comment]
> @clouden90 's comment 1: Use the recenter app of SOCA. In the feature/letkf branch there is a ready example for preparing it.
> 
> beach_umbrella smile parasol_on_ground tropical_drink

https://github.com/JCSDA/soca/blob/develop/test/testinput/ensrecenter.yml

**Review by ShastriPaturi — CHANGES_REQUESTED** [review]
in Jobs/JJOB_HOFX_PREP: line 113
Replace:
cp -p ${SOCA_ANALYSIS}/$CDATE/Data/ocn.socagodas.an.${bkg_date}.nc $RUNCDATE/INPUT_MOM6/MOM.res.nc
with
cp -p ${SOCA_ANALYSIS}/${CDATE}_IC/MOM.res.nc $RUNCDATE/INPUT_MOM6/MOM.res.nc

The ocn.socagodas.an.${bkg_date}.nc file is missing the U-compoenet velocity and the soca_gridgen in da_prep_soca fails

Otherwise, the 3DVAR works and with the above-mentioned change, the hofx works too.

**Comment by clouden90** [comment]
> @clouden90 's comment 1: Use the recenter app of SOCA. In the feature/letkf branch there is a ready example for preparing it.
> 
> 🏖️ 😄 ⛱️ 🍹

**Comment by clouden90** [comment]
> @clouden90 's comment 1: Use the recenter app of SOCA. In the feature/letkf branch there is a ready example for preparing it.
> 
> 🏖️ 😄 ⛱️ 🍹

@flampouris, Thx for the info. Sorry to bother you but I have another question: The vertical coordinate of mom6 state variables is 3D (changes both horizontally & vertically), but the current version of UMD-LETKF only supports 1D vertical coordinate (in letkf.yaml: vtgrid:vert1d), I am wondering if this will cause any issues during DA process, especially for the profile data?

**Review by ShastriPaturi — APPROVED** [review]
Looks good @jkbk2004

**Pull request merged**
