### PR TITLE
Processing the icec EMC files from native to ioda

### PR DESCRIPTION
**Pull request by YanHao-NOAA**
Updated the scripts to convert emc-ice to ioda.

### CODE REVIEW

**Comment by flampouris** [comment]
@jkbk2004 Wait for this PR.

**Comment by YanHao-NOAA** [comment]
I updated the scripts to include a check if ice_emc files exist on $PDY.

**Comment by YanHao-NOAA** [comment]
@jkbk2004 I merged develop to feature/process_ice. Please go ahead to review the code.

**Review by flampouris — COMMENTED** [review]
@YanHao-NOAA I have the impression that you had written the conversion for each satellite individually, didn't you?

**Comment by YanHao-NOAA** [comment]
This version combined both satellites, since Bob suggested to use both.

**Comment by flampouris** [comment]
Thank you for the clarification. The reason that we prefer the obs to be
into different files, is to apply targeted filtering during QC.

Let's finish with this PR and we will address this issue in the next update.

**Comment by jkbk2004** [comment]
> Thank you for the clarification. The reason that we prefer the obs to be into different files, is to apply targeted filtering during QC. Let's finish with this PR and we will address this issue in the next update.

@YanHao-NOAA @flampouris I was testing with wrong branch. I will make another test with right one this evening and let you know.

**Comment by jkbk2004** [comment]
@flampouris @YanHao-NOAA some of the variables in icec_prep_obs.sh comes empty when the script runs. Stelios points that we have to make sure da prep should run first before obs prep. After we figure this issue out, then we can merge this branch.

**Comment by flampouris** [comment]
The order is correct: Obs_prep has to run before da_prep. But the YAML
files needed for the DA have to be prepared at the DA_PREP, similarly to
the other observations.

**Comment by flampouris** [comment]
Closed because of #103

**Pull request closed without merging**
